sudo: required
language: generic
service:
  - docker

before_install:
  - docker build -f client/Dockerfile.dev -t akshaykmr080/fibonacci-react ./client
script:
  - docker run -e CI=true akshaykmr080/fibonacci-react npm run test -- --coverage

after_success:
  - docker build -t akshaykmr080/fibo-complex-api-server ./api-server
  - docker build -t akshaykmr080/fibo-complex-client ./client
  - docker build -t akshaykmr080/fibo-complex-nginx ./nginx
  - docker build -t akshaykmr080/fibo-complex-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker
  - docker push akshaykmr080/fibo-complex-api-server
  - docker push akshaykmr080/fibo-complex-client
  - docker push akshaykmr080/fibo-complex-nginx
  - docker push akshaykmr080/fibo-complex-worker

