sudo: required
language: generic
service:
  - docker

before_install:
  - docker build -f client/Dockerfile.dev -t shreekan/fibonacci-react ./client
script:
  - docker run -e CI=true shreekan/fibonacci-react npm run test -- --coverage

after_success:
  - docker build -t shreekan/fibo-complex-api-server ./api-server
  - docker build -t shreekan/fibo-complex-client ./client
  - docker build -t shreekan/fibo-complex-nginx ./nginx
  - docker build -t shreekan/fibo-complex-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker
  - docker push shreekan/fibo-complex-api-server
  - docker push shreekan/fibo-complex-client
  - docker push shreekan/fibo-complex-nginx
  - docker push shreekan/fibo-complex-worker

  deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-west-2-137991398143"
    bucket_path: "multi-docker"
    on:
      branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"

